# https://fallguysultimateknockout.gamepedia.com/Rounds

rounds_info_dict = {
    # Race
    'round_biggestfan': {'Name': 'Big Fans', 
                        'Type': 'Race', 
                        'Introducted': 2},
    'round_gauntlet_02': {'Name': 'Dizzy Heights', 
                         'Type': 'Race', 
                         'Introducted': 1},
    'round_door_dash': {'Name': 'Door Dash', 
                       'Type': 'Race', 
                       'Introducted': 1},
    'round_dodge_fall': {'Name': 'Fruit Chute', 
                        'Type': 'Race', 
                        'Introducted': 1},
    'round_chompchomp': {'Name': 'Gate Crash', 
                        'Type': 'Race', 
                        'Introducted': 1},
    'round_gauntlet_01': {'Name': 'Hit Parade', 
                         'Type': 'Race', 
                         'Introducted': 1},
    'round_see_saw': {'Name': 'See Saw', 
                     'Type': 'Race', 
                     'Introducted': 1},
    'round_lava': {'Name': 'Slime Climb', 
                  'Type': 'Race', 
                  'Introducted': 1},
    'round_tip_toe': {'Name': 'Tip Toe', 
                     'Type': 'Race', 
                     'Introducted': 1},
    'round_gauntlet_03': {'Name': 'The Whirlygig', 
                         'Type': 'Race', 
                         'Introducted': 1},
    'round_gauntlet_04': {'Name': 'Knight Fever', 
                         'Type': 'Race', 
                         'Introducted': 2},
    'round_wall_guys': {'Name': 'Wall Guys', 
                       'Type': 'Race', 
                       'Introducted': 2},
    'round_iceclimb': {'Name': 'Freezy Peak', 
                       'Type': 'Race', 
                       'Introducted': 3},
    'round_skeefall': {'Name': 'Ski Fall', 
                       'Type': 'Race', 
                       'Introducted': 3},
    'round_gauntlet_05': {'Name': 'Tundra Run', 
                          'Type': 'Race', 
                          'Introducted': 3},
    
    # Survival
    'round_block_party': {'Name': 'Block Party', 
                         'Type': 'Survival', 
                         'Introducted': 1},
    'round_tunnel': {'Name': 'Roll Out', 
                    'Type': 'Survival', 
                    'Introducted': 1},
    'round_jump_club': {'Name': 'Jump Club', 
                       'Type': 'Survival', 
                       'Introducted': 1},
    'round_snowballsurvival': {'Name': 'Snowball Survival', 
                               'Type': 'Survival', 
                               'Introducted': 3},
    
    
    # Hunt
    'round_tail_tag': {'Name': 'Tail Tag', 
                      'Type': 'Hunt', 
                      'Introducted': 1},
    'round_hoops_blockade_solo': {'Name': 'Hoopsie Legends', 
                                 'Type': 'Hunt', 
                                 'Introducted': 2},
    
    # Logic
    'round_match_fall': {'Name': 'Perfect Match', 
                        'Type': 'Logic', 
                        'Introducted': 1},
    
    # Team
    'round_egg_grab': {'Name': 'Egg Scramble', 
                      'Type': 'Team', 
                      'Introducted': 1},
    'round_fall_ball_60_players': {'Name': 'Fall Ball', 
                                  'Type': 'Team', 
                                  'Introducted': 1},
    'round_ballhogs': {'Name': 'Hoarders', 
                      'Type': 'Team', 
                      'Introducted': 1},
    'round_hoops': {'Name': 'Hoopsie Daisy', 
                   'Type': 'Team', 
                   'Introducted': 1},
    'round_jinxed': {'Name': 'Jinxed', 
                    'Type': 'Team', 
                    'Introducted': 1},
    'round_conveyor_arena': {'Name': 'Team Tail Tag', 
                            'Type': 'Team', 
                            'Introducted': 1},
    'round_rocknroll': {'Name': "Rock 'N' Roll", 
                       'Type': 'Team', 
                       'Introducted': 1},
    'round_egg_grab_02': {'Name': 'Egg Siege', 
                         'Type': 'Team', 
                         'Introducted': 2},
    'round_snowy_scrap': {'Name': 'Snowy Scrap', 
                          'Type': 'Team', 
                          'Introducted': 3},
    'round_chicken_chase': {'Name': 'Pegwin Pursuit', 
                            'Type': 'Team', 
                            'Introducted': 3},
    
    # Finals
    'round_jump_showdown': {'Name': 'Jump Showdown', 
                           'Type': 'Final', 'Introducted': 1},
    'round_floor_fall': {'Name': 'Hex-A-Gone', 
                        'Type': 'Final', 
                        'Introducted': 1},
    'round_fall_mountain_hub_complete': {'Name': 'Fall Mountain', 
                                        'Type': 'Final', 
                                        'Introducted': 1},
    'round_royal_rumble': {'Name': 'Royal Fumble', 
                           'Type': 'Final', 
                           'Introducted': 1}, 
    'round_thin_ice': {'Name': 'Thin Ice', 
                       'Type': 'Final', 
                       'Introducted': 3},
    'round_tunnel_final': {'Name': 'Roll Off', 
                           'Type': 'Final', 
                           'Introducted': 3},
}

# '': {'Name': '', 'Type': '', 'Introducted': 3},

list_of_finals = ['round_fall_mountain', 'round_floor_fall', 'round_royal_rumble', 'round_jump_showdown', 
                  'round_fall_mountain_hub_complete', 'round_thin_ice', 'round_tunnel_final', 
                  'round_floor_fall_event_only_final', 'round_jump_showdown_jump_club_event_only_final', ]

show_type_dict = {
    'main_show': 'Main Show',
    'event_only_survival_3010_to_0511': 'Slime Survivors',
    'event_only_season_2_variation_1011_to_1611': 'Medieval Mix Up',
    'event_only_hard_mode_2111_to_2711': 'Hard Mode',
    'event_season_3_highlight_1512_to_1912': 'Season 3',
    'event_only_floor_fall_0501_to_0701': 'Hex-a-gone Trials',
    'event_only_jump_club_1202_to_1402_2021': 'Jump Around'
}

starting_races = ['round_biggestfan', 'round_gauntlet_02', 'round_door_dash', 
                  'round_chompchomp', 'round_gauntlet_01', 'round_see_saw', 
                  'round_gauntlet_03', 'round_gauntlet_04', 'round_gauntlet_05']


